services:
    dameerv_sylius_supplier_plugin.controller.supplier_slug:
        class: Dameerv\SyliusSupplierPlugin\Controller\SupplierSlugController
        public: true
        arguments:
            - '@sylius.generator.slug'
