services:
    dameerv_sylius_supplier_plugin.sitemap_provider.supplier:
        class: Dameerv\SyliusSupplierPlugin\SitemapProvider\SupplierUrlProvider
        arguments:
            - '@dameerv_sylius_supplier_plugin.repository.supplier'
            - '@router'
            - '@sylius.sitemap_url_factory'
            - '@sylius.sitemap_url_alternative_factory'
            - '@sylius.context.locale'
        tags:
            - { name: sylius.sitemap_provider }
