sylius_ui:
    events:
        dameerv_sylius_supplier_plugin.shop.supplier.product.index.before_vertical_menu:
            blocks:
                legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    context:
                        event: dameerv_sylius_supplier_plugin.shop.supplier.product.index.before_vertical_menu

        dameerv_sylius_supplier_plugin.shop.supplier.product.index.after_vertical_menu:
            blocks:
                legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    context:
                        event: dameerv_sylius_supplier_plugin.shop.supplier.product.index.after_vertical_menu

        dameerv_sylius_supplier_plugin.shop.supplier.product.index.before_list:
            blocks:
                legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    context:
                        event: dameerv_sylius_supplier_plugin.shop.supplier.product.index.before_list

        dameerv_sylius_supplier_plugin.shop.supplier.product.index.before_pagination:
            blocks:
                legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    context:
                        event: dameerv_sylius_supplier_plugin.shop.supplier.product.index.before_pagination

        dameerv_sylius_supplier_plugin.shop.supplier.product.index.search:
            blocks:
                before_search_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 35
                    context:
                        event: dameerv_sylius_supplier_plugin.shop.supplier.product.index.before_search
                search:
                    template: "@DameervSyliusSupplierPlugin/Shop/Supplier/Product/Index/_search.html.twig"
                    priority: 30
                after_search_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 25
                    context:
                        event: dameerv_sylius_supplier_plugin.shop.supplier.product.index.after_search
                pagination:
                    template: "@DameervSyliusSupplierPlugin/Shop/Supplier/Product/Index/_pagination.html.twig"
                    priority: 20
                sorting:
                    template: "@DameervSyliusSupplierPlugin/Shop/Supplier/Product/Index/_sorting.html.twig"
                    priority: 10

        dameerv_sylius_supplier_plugin.shop.supplier.index.header:
            blocks:
                breadcrumb:
                    template: "@DameervSyliusSupplierPlugin/Shop/Supplier/Header/_breadcrumb.html.twig"
                    priority: 20
                before_header_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 15
                    context:
                        event: dameerv_sylius_supplier_plugin.shop.supplier.index.header.before
                header:
                    template: "@DameervSyliusSupplierPlugin/Shop/Supplier/Header/_content.html.twig"
                    priority: 10
                after_header_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        event: dameerv_sylius_supplier_plugin.shop.supplier.index.header.after

        dameerv_sylius_supplier_plugin.shop.supplier.index.before_pagination:
            blocks:
                legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    context:
                        event: dameerv_sylius_supplier_plugin.shop.supplier.index.before_pagination

        dameerv_sylius_supplier_plugin.shop.supplier.index.search:
            blocks:
                before_search_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 35
                    context:
                        event: dameerv_sylius_supplier_plugin.shop.supplier.index.before_search
                search:
                    template: "@DameervSyliusSupplierPlugin/Shop/Supplier/Index/_search.html.twig"
                    priority: 30
                after_search_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 25
                    context:
                        event: dameerv_sylius_supplier_plugin.shop.supplier.index.after_search
                pagination:
                    template: "@DameervSyliusSupplierPlugin/Shop/Supplier/Index/_pagination.html.twig"
                    priority: 20
                sorting:
                    template: "@DameervSyliusSupplierPlugin/Shop/Supplier/Index/_sorting.html.twig"
                    priority: 10

        dameerv_sylius_supplier_plugin.shop.supplier.index.list:
            blocks:
                before_list_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 25
                    context:
                        event: dameerv_sylius_supplier_plugin.shop.supplier.index.before_list
                list:
                    template: "@DameervSyliusSupplierPlugin/Shop/Supplier/Index/_list.html.twig"
                    priority: 20
                after_list_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 15
                    context:
                        event: dameerv_sylius_supplier_plugin.shop.supplier.index.after_list
