sylius_grid:
    grids:
        dameerv_sylius_supplier_plugin_shop_supplier:
            driver:
                name: doctrine/orm
                options:
                    class: "%dameerv_sylius_supplier_plugin.model.supplier.class%"
                    repository:
                        method: createShopListQueryBuilder
                        arguments:
                            channel: "expr:service('sylius.context.channel').getChannel()"
                            sorting: "expr:service('request_stack').getCurrentRequest().get('sorting', [])"
            sorting:
                position: asc
            limits: [12, 24, 36]
            fields:
                createdAt:
                    type: datetime
                    sortable: ~
                position:
                    type: string
                    sortable: ~
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: ~
            filters:
                search:
                    type: shop_string
                    label: false
                    options:
                        fields: [name]
                    form_options:
                        type: contains
