Dameerv\SyliusSupplierPlugin\Entity\SupplierEmail:
    constraints:
        - Symfony\Bridge\Doctrine\Supplier\Constraints\UniqueEntity:
            fields: [supplier, value]
            errorPath: value
            message: 'dameerv_sylius_supplier_plugin.supplier.email.unique'
            groups: ['dameerv']
    properties:
        value:
            - NotBlank:
                message: 'dameerv_sylius_supplier_plugin.supplier.email.not_blank'
                groups: ['dameerv']
            - Length:
                min: 2
                max: 250
                minMessage: 'dameerv_sylius_supplier_plugin.supplier.email.min_length'
                maxMessage: 'dameerv_sylius_supplier_plugin.supplier.email.max_length'
                groups: ['dameerv']
            - Email:
                message: 'dameerv_sylius_supplier_plugin.supplier.email.invalid'
                mode: strict
                groups: ['dameerv']
