Dameerv\SyliusSupplierPlugin\Entity\Supplier:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name]
            message: 'dameerv_sylius_supplier_plugin.supplier.name.unique'
            groups: ['dameerv']
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [slug]
            message: 'dameerv_sylius_supplier_plugin.supplier.slug.unique'
            groups: ['dameerv']
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [email]
            message: 'dameerv_sylius_supplier_plugin.supplier.email.unique'
            groups: ['dameerv']
    properties:
        name:
            - NotBlank:
                message: 'dameerv_sylius_supplier_plugin.supplier.name.not_blank'
                groups: ['dameerv']
            - Length:
                min: 2
                max: 250
                minMessage: 'dameerv_sylius_supplier_plugin.supplier.name.min_length'
                maxMessage: 'dameerv_sylius_supplier_plugin.supplier.name.max_length'
                groups: ['dameerv']
        slug:
            - NotBlank:
                message: 'dameerv_sylius_supplier_plugin.supplier.slug.not_blank'
                groups: ['dameerv']
            - Length:
                min: 2
                max: 250
                minMessage: 'dameerv_sylius_supplier_plugin.supplier.slug.min_length'
                maxMessage: 'dameerv_sylius_supplier_plugin.supplier.slug.max_length'
                groups: ['dameerv']
        email:
            - NotBlank:
                message: 'dameerv_sylius_supplier_plugin.supplier.email.not_blank'
                groups: ['dameerv']
            - Length:
                min: 2
                max: 250
                minMessage: 'dameerv_sylius_supplier_plugin.supplier.email.min_length'
                maxMessage: 'dameerv_sylius_supplier_plugin.supplier.email.max_length'
                groups: ['dameerv']
            - Email:
                message: 'dameerv_sylius_supplier_plugin.supplier.email.invalid'
                mode: strict
                groups: ['dameerv']
        logoFile:
            - NotBlank:
                message: 'dameerv_sylius_supplier_plugin.supplier.logo_file.not_blank'
                groups: ['dameerv_logo_create']
        translations:
            - Valid: ~
        extraEmails:
            - Valid: ~
