dameerv_sylius_supplier_plugin_shop_partial_supplier_show_by_slug:
    path: /by-slug/{slug}
    methods: [GET]
    defaults:
        _controller: dameerv_sylius_supplier_plugin.controller.supplier:showAction
        _sylius:
            template: $template
            repository:
                method: findOneBySlug
                arguments:
                    - $slug
                    - "expr:service('sylius.context.locale').getLocaleCode()"
    requirements:
        slug: .+

dameerv_sylius_supplier_plugin_shop_partial_supplier_index_by_channel:
    path: /by-channel
    methods: [GET]
    defaults:
        _controller: dameerv_sylius_supplier_plugin.controller.supplier:indexAction
        _sylius:
            template: $template
            repository:
                method: findByChannel
                arguments:
                    - "expr:service('sylius.context.channel').getChannel()"
